configutil/config.go
configutil/kms.go

Long term, we should make an options pattern for configutil so that we
can have the program decide on the max number of blocks.

Update max `kms` blocks and fix error message

---

awsutil/options.go
awsutil/options_test.go
awsutil/rotate.go
awsutil/rotate_test.go

This adds the GetCallerIdentity call, which allows for a set of
credentials/session to get information on its effective account ID and
principal ARN.
This can be useful in checking the validity of credentials, as it
requires no permissions to run other than the access key to be usable.
For info on the call, see:
https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html

awsutil: add GetCallerIdentity

---

awsutil/options.go
awsutil/options_test.go
awsutil/rotate.go
awsutil/rotate_test.go

This adds GetCallerIdentity to CreateAccessKey and RotateKeys. The
latter is done simply by passing WithTimeout through to the inner
CreateAccessKey on Rotate. As such, both paths are conditional on a
non-zero WithTimeout option being given - this is to ensure that we
don't try to immediately verify, which is likely to always fail.

awsutil: add GetCallerIdentity to Create/Rotate

---

awsutil/generate_credentials.go

This PR uses the Profile field that already existed in the AWS Credentials Config. It reads from the `AWS_PROFILE` environment variable and uses this value in the `GenerateCredentialChain` method to enable the Shared Credentials Provider. 
The addition of these changes allows the use of `source_profile` fields that point to a named profile with credentials for assuming roles. This aims to fix:
- https://github.com/hashicorp/vault/issues/5767
- https://github.com/hashicorp/terraform-provider-vault/issues/1086 (TFVP issue related to above Vault issue)

Read `AWS_PROFILE` to enable Shared Credentials provider

---

awsutil/clients.go
awsutil/clients_test.go
awsutil/mocks.go
awsutil/mocks_test.go
awsutil/options.go
awsutil/options_test.go
awsutil/rotate.go
awsutil/rotate_test.go

This adds the ability to supply mock IAM and STS interfaces to use with
the RotateKeys, CreateAccessKey, DeleteAccessKey, and GetCallerIdentity
methods.
Additionally, work has been done to incorporate the existing IAM mock
object into the package, in addition to adding a similar STS mock that
allows for the mocking of the GetCallerIdentity method.
Factory functions are also included to allow these to be incorporated
seamlessly into the call path, in addition to allowing for introspection
into any session data being received by the constructor functions.

awsutil: add ability to mock IAM and STS APIs

---

strutil/go.mod
strutil/go.sum
strutil/strutil.go
strutil/strutil_benchmark_test.go
strutil/strutil_test.go

I noticed some pretty quick-and-easy wins for performance in the strutil package.
1. Use `struct{}` instead of `bool` for map membership. The empty struct does not allocate and consumes no memory, so it's far more efficient than a boolean:
```go
package main
import (
"fmt"
"unsafe"
)
func main() {
x := [100]struct{}{}
y := [100]bool{}
fmt.Printf("%v\n", unsafe.Sizeof(x)) // 0
fmt.Printf("%v\n", unsafe.Sizeof(y)) // 100
}
```
1. Pre-allocate slices and maps when we know the maximum possible size.
1. Remove an unnecessary test dependency and rename the tests to match Go's expected test format name.
Before:
```text
BenchmarkRemoveDuplicates-16          	       2	 756790682 ns/op	106821536 B/op	   38192 allocs/op
BenchmarkRemoveDuplicatesStable-16    	       6	 183990038 ns/op	58343824 B/op …
```

Minimize allocations in strutil

---

mlock/mlock_unavail.go

Using `GOOS=android` matches build tags and files as for `GOOS=linux` in addition to android tags and files.
See https://groups.google.com/g/golang-nuts/c/ZTGMjhEV7uY for further details.
Without this change when using `gomobile bind` I see the following error:
```
../pkg/mod/github.com/hashicorp/go-secure-stdlib/mlock@v0.1.1/mlock_unix.go:15:6: lockMemory redeclared in this block
/tmp/gomobile-work-2337392267/pkg/mod/github.com/hashicorp/go-secure-stdlib/mlock@v0.1.1/mlock_unavail.go:9:19: previous declaration
```

mlock: Remove android build tag

---

listenerutil/error.go
listenerutil/forwarded_for.go
listenerutil/forwarded_for_test.go
listenerutil/go.mod
listenerutil/go.sum

- `TrustedFromXForwardedFor` uses the XForwardedFor* listener cfg setting to determine how/if headers are trusted/allowed for inbound http requests
- `WrapForwardedForHandler` which is an http middleware wrapper that uses `TrustedFromXForwardedFor` to determine how/if headers are trusted/allowed for inbound http requests

feature: Add support handling forwarded for headers 

---

configutil/config.go
configutil/config_test.go

A user is now able to set cluster_name in their HCL to point to an environment variable (env://) or file (file://) and the logic will dynamically resolve the value within and assign it to the field.

feat(configutil): Add env and file support to ClusterName

---

listenerutil/parse.go
listenerutil/parse_test.go

The deprecated fields, `TLSKeyFile` and `TLSClientCAFile` are limited in terms of functionality: They only accept a path to a file containing their respective values.
The newly introduced fields `TLSKey` and `TLSClientCA` are more versatile: They abstract away the file limitation and contain the actual values. You can set these values directly, source them from an environment variable using the `env://` URL, or from a file using the `file://` URL.

feat(listener): New TLS fields to support env and file sourcing

---

parseutil/parseutil.go
parseutil/parseutil_test.go

The Vault SSH secrets engine presently supports specifying allowed key
sizes in a field of type `map[string]int`. The notable limitation of this
type is that it cannot handle algorithms for which multiple key lengths
are allowed, e.g., allowing both 2048 and 4096-bit RSA keys. It relies
on `parseutil` to handle this conversion (for each element of the map,
calling `ParseInt(...)`).
A better type is `map[string][]int`; this allows explicitly specifying
multiple allowed key lengths and giving flexibility to the operator over
whether or not to restrict uncommon or intermediate key sizes (e.g.,
prohibiting 3072-bit RSA keys if certain deployed implementations are
not compatible -- though this is unlikely in practice).
While the SSH module can maintain this parsing logic, it'd be nice to …

feat(parseutil) Support parsing slices of ints

---

parseutil/parseutil.go
parseutil/parseutil_test.go

The `ParseCommaStringSlice` function in `parseutil` performs a type assertion (i.e. `in.(string)`) but does not return an error if the assertion fails. Without an early return, a panic might occur in the `mapstructure.NewDecoder` call. `StringToSliceHookFunc` in `mapstructure` returns a hook func that performs a similar string type assertion but [does not verify that it was successful](https://github.com/mitchellh/mapstructure/blob/1b7c3d8e219d00abb1d9267545c50c6c12fee562/decode_hooks.go#L91). This can occur if the input is a `json.Number` given that its `reflect.Kind` is `string`. The type assertion in `mapstructure` will panic with `invalid type assertion: data.(string) (non-interface type json.Number on left)`.
Unit tests for `ParseCommaStringSlice` were also added as there weren't any …

Handle JSON Number in ParseCommaStringSlice

---

kv-builder/builder.go
kv-builder/builder_test.go

The KV Builder panics when attempting to process a single backslash. The KV Builder `add` method currently assumes that the provided string has at least two characters when attempting to check for an escaped `@` (i.e. `\@`). The proposed fix is to guard with a length check.
In additional to the added unit test, this change was functionally tested with the Vault kv secret engine CLI.
Before change:
```
❯ vault kv put secret/foo 'bar=\'
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/hashicorp/go-secure-stdlib/kv-builder.(*Builder).add(0xc0008cb440, {0x7ffeefbff898, 0x11880ee8})
/Users/ccapurso/go/pkg/mod/github.com/hashicorp/go-secure-stdlib/kv-builder@v0.1.1/builder.go:94 +0x832
github.com/hashicorp/go-secure-stdlib/kv-builder.(*Builder).Add(0x7 …
```

fix kv builder out of bounds panic on single backslash

---

configutil/Makefile
configutil/file_plugin_test.go
configutil/go.mod
configutil/go.sum
configutil/kms.go
configutil/testplugins/aead/main.go
pluginutil/go.mod
pluginutil/go.sum
pluginutil/options.go
pluginutil/options_test.go
pluginutil/pluginutil.go

This contains two items:
1. In pluginutil, allows a direct plugin path to be specified, along with a (required) checksum and (optional) hash method used to generate the checksum. This is via an option that then factors into building the plugin map, and some plugin launching changes to understand these types.
2. In configutil, support for this new feature for KMS plugins. Additionally, the ability to specify this information within KMS blocks in HCL.
Tagging @jimlambrt for review, @calvn and @sgmiller mostly for heads-up.

Allow plugins to be specified as direct file paths

---

parseutil/parseutil.go
parseutil/parseutil_test.go

These proposed variants allow parsing smaller data types (such as `int`s)
from larger data types (the `int64` returned by `ParseInt{,Slice}(...)`),
validating that they are within the requested range prior to casting.
With the `SafeParseIntRange(...)` helper, we also allow validation of the
maximum expected number of elements in the slice.
`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`
--
https://hashicorp.atlassian.net/browse/VAULT-3892 has some context around this change for those with access.

feat(parseutil) Add Safe variants of ParseInt*

---

fileutil/LICENSE
fileutil/caching_file_reader.go
fileutil/caching_file_reader_test.go
fileutil/go.mod

Adds a fileutil package, mainly for the purpose of sharing the caching file reader from https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/main/caching_file_reader.go

adding fileutil

---

configutil/Makefile
configutil/kms.go
configutil/kms_test.go
configutil/testplugins/aead/main.go

It seems we forgot to include this when migrating to the new kms wrapper in #32.
The testplugin as previously implemented didn't support the Encrypt or Decrypt methods, since it did not have an AEAD cipher configured. This change configures an AES cipher with a hardcoded key, so that we can do Encrypt
and Decrypt operations in tests.
The configureWrapper was not propagating plugin options. Propagate these options and add a test to ensure they work.

Propagate plugin options in ConfigureWrapper

---

configutil/config_test.go
configutil/go.mod
configutil/go.sum
listenerutil/go.mod
listenerutil/go.sum
listenerutil/handler.go
listenerutil/handler_test.go
listenerutil/listener.go
listenerutil/parse.go
reloadutil/reload_test.go

adds two additional configuration settings to the `listener` config section:
`custom_api_response_headers` and `custom_ui_response_headers`
this update also adds `WrapCustomHeadersHandler` wrapper which includes all of the logic necessary to perform custom header injection automatically

Add Custom Headers To Config Parser

---

configutil/config_test.go
listenerutil/handler_test.go
listenerutil/parse.go

Replaces all instances of `data:*` with `data:` to correctly set the `img-src` policy of the default `content-security-policy`.
`data:*` does not correctly allow `data:image/png;base64,...` type inline images, but `data:` does

Fix Default CSP img-src

---

listenerutil/handler.go
listenerutil/handler_go119.go
listenerutil/handler_go120.go
listenerutil/handler_test.go

Using the new http.ResponseController in Go 1.20, we can easily add support for http.Flusher, http.Hijacker, http.Pusher and the SetReadDeadline and SetWriteDeadline methods to the ResponseWriter wrapper. This fixes some services that rely on this interface being implemented for their functionality.
In Go 1.19, just implement Flusher, Pusher and Hijacker explicitly.

listenerutil: Support http.Flusher, http.Hijacker, http.Pusher

---

awsutil/mocks.go
awsutil/mocks_test.go

Just a little bit of code to add a ListAccessKeys mock stub to awsutil.
Over in eco-applications we're adding some aws functionality and having this additional function available in the mock would be helpful, and it was mentioned that I should just go ahead and offer a PR for it.

awsutil: add a mock ListAccessKeys pair

---

awsutil/generate_credentials.go
awsutil/go.mod
awsutil/go.sum
awsutil/options.go
awsutil/options_test.go

This PR enables the ability to add ec2-instance role providers to the credential chain for awsutil.
- Added the following options to support ec2-instance role provider: WithRoleExternalId, WithRoleTags, WithWebIdentityTokenFile, WithRoleSessionName, WithRoleArn
- GenerateCredentialChain() will append a ec2-instance role provider to the provider chain when roleARN is not empty and WebIdentityTokenFile is empty.

feat: support adding ec2-instance role provider

---

nonceutil/benchmark_test.go
nonceutil/encrypted_nonce.go
nonceutil/go.mod
nonceutil/go.sum
nonceutil/nonce.go
nonceutil/nonce_test.go
nonceutil/sync_map_nonce.go

This migrates nonceutil from `vault/sdk/helper/nonce` into `go-secure-stdlib`. The first commit is a direct port to be `diff`able, the second modifies the copyright headers and a few extra comments, and the third adds the package's `go.mod`/`go.sum` files.
This nonce service was added in https://github.com/hashicorp/vault/pull/20688 and was intended for ACME with a better performance characteristics than the old implementation (preserved in `sync_map_nonce.go`).

feat(nonceutil): Add new nonce library

---

awsutil/generate_credentials.go
awsutil/options.go
awsutil/options_test.go

Adds field `WebIdentityToken` to `CredentialsConfig{}`, along with a simple TokenFetcher to use the contents of a token in the WebIdentityProvider, instead of the path to a token file. Useful when working with a token requested directly for an EKS/k8s service account configured with IRSA, for example.
Used in https://github.com/hashicorp/vault-secrets-operator/pull/235

awsutil: adding WebIdentityToken to CredentialsConfig{}

---

awsutil/generate_credentials.go

https://github.com/hashicorp/go-secure-stdlib/pull/57 caused a regression in Vault. In that PR the AWS environment variable checks in GenerateCredentialChain were moved to NewCredentialsConfig for AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE, and AWS_ROLE_SESSION_NAME. This caused users of the awsutil library that call GenerateCredentialConfig to fail to set the above values if they are depending on env variables to be read.
Another solution could be to find all users of go-secure-stdlib’s awsutil and ensure env vars are properly read and set in the config before calling GenerateCredentialConfig like in https://github.com/hashicorp/vault/pull/21930. However, I think a this PR is a better resolution. With this change we shouldn't have to make any changes anywhere else.
This change was tested …

awsutil: ensure GenerateCredentialChain checks envs

---

.github/workflows/go.yml
listenerutil/go.mod
listenerutil/handler_go119.go
listenerutil/handler_go120.go
mlock/go.mod
parseutil/go.mod
password/go.mod

Adding all of GitHub's suggested reviewers, but feel free to forward me on to other reviewers.
I noticed in #84 that the CI passes even if there are failures in the build and/or test, see here for an example on main: https://github.com/hashicorp/go-secure-stdlib/actions/runs/5602106840. See here for an example of the changes from this PR: https://github.com/hashicorp/go-secure-stdlib/actions/runs/5962737784
While we could probably fix it up with some bash wizardry, I also thought it seemed worthwhile to allow submodules to have their own Go version requirements, so I made a matrix strategy and also added an introspecting `verify-ci` step that ensures people don't forget to add their own module when they create new modules.
Finally, there are a few minor fixes, mostly where a module was …

Ensure CI fails if tests fail

---

.github/workflows/go.yml
plugincontainer/container_runner.go
plugincontainer/container_runner_test.go

gVisor's runsc only supports "private" and "slave" modes, and we don't need any propagation anyway so just default to private. See here for some good documentation on the setting: https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation
In particular:
> `private`: The mount is private. Sub-mounts within it are not exposed to replica mounts, and sub-mounts of replica mounts are not exposed to the original mount.

Set unix socket volume's bind mount propagation to private

---

plugincontainer/config.go
plugincontainer/container_reattach.go
plugincontainer/container_runner.go
plugincontainer/container_runner_test.go
plugincontainer/examples/container/main.go
plugincontainer/go.mod
plugincontainer/go.sum

This makes several breaking API changes, so will necessitate a bump to v0.2.0, but should provide us with a better API in the longer term.
Builds on the additions in https://github.com/hashicorp/go-plugin/pull/277 to enable dropping all default capabilities from the plugin container. We now let go-plugin set the PLUGIN_UNIX_SOCKET_GROUP env var, and override the value it sets for PLUGIN_UNIX_SOCKET_DIR because the plugin's view of that directory is different. As a result, renamed `UnixSocketGroup` as `GroupAdd` to more accurately reflect that it now only controls the container's GroupAdd setting.
As that requires a breaking change, I also updated the API for creating a RunnerFunc to make it a bit cleaner and reduce unnecessarily exported API surface like `ContainerRunner` which was …

plugincontainer: Drop all capabilities from plugin containers

---

plugincontainer/container_runner.go

Found in manual testing of the Vault release 1.15.0-rc1
The context passed to `Start` by go-plugin is cancelled once the plugin has successfully started and communicated its address, but the lifetime of the container log streaming needs to be uncoupled from that. The log streaming will stop when it encounters an EOF error, which will happen when the container is killed.

plugincontainer: Fix container logs context to have no timeout/cancel

---

.github/workflows/go.yml
plugincontainer/compatibility_matrix_test.go
plugincontainer/config.go
plugincontainer/container_runner.go
plugincontainer/container_runner_external_test.go
plugincontainer/examples/container/Dockerfile
plugincontainer/examples/container/plugin-counter/main.go
plugincontainer/go.mod
plugincontainer/go.sum

Support running as non-root container users under rootless container runtimes.
* Adds a new configuration option `Config.Rootless`, which should be used when both the runtime and the container user are running as non-root. It sets up default ACLs on the host socket directory, and gives the container the DAC_OVERRIDE capability to ensure each side can write to the shared Unix socket and folder despite each being owned by one side and the other side being a different user on the host.
* Pulls in https://github.com/hashicorp/go-plugin/pull/288 and uses the new `GRPCBrokerMultiplexing` option to eliminate host-side sockets and reduce the `--host-uds` flag from `all` to `create`, which means no Unix domain sockets from the host will ever be available inside gVisor containers.
* Stop skipping …

plugincontainer: Support plugins in rootless runtime with nonroot user

---

awsutil/generate_credentials.go
awsutil/options.go
awsutil/options_test.go

This PR introduces the ability to set a custom token fetcher in the `awsutil/v0` package. This PR involves adding the token fetcher to the credential config and ensuring that the token fetcher can be used by to generate the credential chain if provided in the cred config.
The actual token fetcher implementation that fetches the Identity Token is in Vault here:

Add ability to set a custom identity token fetcher implementation

---

pluginutil/pluginutil.go

Return a blank cleanup func instead of `nil` to prevent accidental panic from `defer cleanup()`

return blank cleanup func for plugin.InmemCreationFunc

---

.github/workflows/go.yml
plugincontainer/examples/container/Dockerfile

Lock the image version used in test, and switch to available commands

plugincontainer: fix image build

---

parseutil/parseutil.go
parseutil/parseutil_test.go

Error out rather than producing negative values when this happens.  Addresses https://hashicorp.atlassian.net/browse/VAULT-5437

Add test for overflow during multiplication in TestParseDurationSeconds.

---

.github/workflows/go.yml
permitpool/example_test.go
permitpool/go.mod
permitpool/go.sum
permitpool/permitpool.go
permitpool/permitpool_test.go

The permitpool module contains a single package that implements a pool of permits, allowing limited number of concurrent executions.

permitpool: add new module

---

cryptoutil/rsa.go

Thinking more about the attack surface of the DRBG and our inability to zero
memory, it seems safer to use the Reseed function of the single DRBG
instance rather than instantiating a new DRBG when needing to reseed.

Avoid more instances of the DRBG in GCable RAM by reseeding rather than regenerating.

---

.github/CODEOWNERS

As the company grows and changes, cross-Secure repos like this cannot be owned by individuals. It was decided that there should be a secure-leads group, containing membership from Staff+ engineers or engineers with significant cross-org ownership.
(I will remove myself from this list as soon as this PR is approved and merged; I was just delegated to set up the group.)

Replace individual ownership with secure-leads team for scalability
